import {Login} from "./Login";
import {Register} from "./Register";
import {Home} from './Home';
import {NotFound} from "./NotFound";
import {AddFiliale} from "./AddFiliale";
import {AllFiliale} from "./AllFiliale";
import { Welcome } from "./Welcome";
import { AddProject } from "./AddProject";
import { AllProjects } from "./AllProjects";
export {Login,Register,Home,NotFound,AddFiliale,Welcome,AllFiliale,AllProjects,AddProject};